apiVersion: v1
entries:
  irc-ui:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-10T11:55:45.004509445Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: cd90c171919668f49f3d2ddc34f0819b0d94ed287e7af25637415a53d834c5c2
    home: instemmingen.conduction.nl
    icon: instemmingen.conduction.nl
    name: irc-ui
    urls:
    - irc-ui-0.1.0.tgz
    version: 0.1.0
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-10T11:55:45.007575944Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 41e391270f36449fab98ba2f332f64a18ead27f0783ab544b5608b71246e34c4
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-10T11:55:44.99218015Z"
